"""Resume: the sealed realization of a named version rebuilt and proven, so sealing can continue.

Before sealing a restart regenerates; after sealing it resumes the named realization,
because model-written prose means reassembly from the seed no longer reproduces the bytes
(the step 14 rulings in DESIGN, "Materialization"). The operator names the version — the
job prints it before its first side effect for exactly this — and the code proves it two
ways before a byte is touched:

1. the sealed world spec is read from the truth bucket and strictly decoded, and its
   generator version must equal the running one, since a resume is not a migration;
2. the semantic world is reassembled from the spec's own provenance — seed, organization
   parameters, world start — and its semantic digest must equal the sealed one, so a
   resume can never continue a world of different meaning;
3. the sealed truth manifest is read and its digest must be the one the world spec cites;
4. the materialization record is decoded from it, and the accepted bodies are lifted from
   the sealed plantings — a comment's remark after its prefix, a section's text;
5. the same ``compose`` and the same ``bundle`` as a fresh run rebuild the realization, and
   the bundle's version must equal the one named — the whole-bundle identity through the
   normal function, which implies the codec round-trips.

What comes back is the composed world and its bundle, exactly what a fresh run hands the
sealing sequence, which then hits the equal case at every key already sealed and continues
from the checkpoint. Auto-discovery of an unfinished version by listing the mutable prefix
was rejected: it needs a rule for more than one, misses the window before the first
checkpoint, and the design avoids guessing; an operator naming the version and the code
verifying it is the honest shape.
"""

from __future__ import annotations

from collections.abc import Callable
from datetime import date

from leaveimpact.adapters.object_store.layout import truth_manifest_key, world_spec_key
from leaveimpact.adapters.object_store.read import ObjectReader
from leaveimpact.core.comments import comment_body
from leaveimpact.core.ids import WorldVersion
from leaveimpact.generator.truth_record import decode_materialization
from leaveimpact.world.artifacts import Bundle, PlantedWorldSpec, bundle, digest, semantic_digest
from leaveimpact.world.assembly import SemanticWorld, WorldSpec, assemble_semantic_world
from leaveimpact.world.briefs import CommentTarget, SectionTarget
from leaveimpact.world.composition import compose
from leaveimpact.world.decoders import decode_world_spec
from leaveimpact.world.org import OrgParams
from leaveimpact.world.version import GENERATOR_VERSION

Assembler = Callable[[int, OrgParams, date], SemanticWorld]
"""The reassembly from provenance a resume proves against; the pure assembly in production."""


class ResumeRefused(Exception):
    """The named version cannot be resumed by this code; the message says which proof failed."""


def resume_world(
    version: WorldVersion, truth: ObjectReader, assemble: Assembler = assemble_semantic_world
) -> tuple[WorldSpec, Bundle]:
    """The composed world and bundle of the sealed ``version``, proven, or ``ResumeRefused``.

    ``assemble`` is the reassembly the semantic digest is proven against — the pure assembly
    in production, a stand-in in tests that seal a world no seed produces.
    """
    spec_object = truth.get(world_spec_key(version))
    if spec_object is None:
        raise ResumeRefused(f"no sealed world spec for {version}: nothing to resume")
    truth_object = truth.get(truth_manifest_key(version))
    if truth_object is None:
        raise ResumeRefused(f"no sealed truth manifest for {version}: nothing to resume")
    planted = decode_world_spec(spec_object.content)
    if planted.generator_version != GENERATOR_VERSION:
        raise ResumeRefused(
            f"{version} was generated by version {planted.generator_version}, this code is "
            f"version {GENERATOR_VERSION}: resume is not a migration"
        )
    semantic = assemble(planted.seed, planted.org.params, planted.world_start)
    if semantic_digest(semantic) != planted.semantic_digest:
        raise ResumeRefused(
            f"{version}: the reassembled semantic world differs from the sealed one "
            f"({semantic_digest(semantic)} against {planted.semantic_digest})"
        )
    if digest(truth_object.content) != planted.truth_manifest_digest:
        raise ResumeRefused(
            f"{version}: the sealed truth manifest is not the one the world spec cites"
        )
    record = decode_materialization(truth_object.content)
    world = compose(semantic, _prose_of(planted, semantic, version), record)
    sealed = bundle(world)
    if sealed.world_version != version:
        raise ResumeRefused(
            f"the rebuilt realization is {sealed.world_version}, not {version}: the sealed "
            "spec does not round-trip to the bundle named"
        )
    return world, sealed


def _prose_of(
    planted: PlantedWorldSpec, semantic: SemanticWorld, version: WorldVersion
) -> dict[str, str]:
    """Every brief's accepted body, lifted from the sealed plantings by target."""
    rows = {row.scenario_id: row for row in planted.scenarios}
    prose: dict[str, str] = {}
    for scenario in semantic.scenarios:
        row = rows.get(scenario.spec.id)
        if row is None:
            raise ResumeRefused(
                f"{version}: the sealed spec has no planting for {scenario.spec.id}"
            )
        for brief in scenario.briefs:
            match brief.target:
                case CommentTarget():
                    comments = [
                        comment
                        for planted_item in row.owned.work_items
                        if planted_item.entity.id == brief.target.work_item_id
                        for comment in planted_item.entity.comments
                        if comment.id == brief.id
                    ]
                    if len(comments) != 1:
                        raise ResumeRefused(f"{version}: the sealed spec holds no {brief.id}")
                    prose[brief.id] = comment_body(comments[0].text)
                case SectionTarget():
                    sections = [
                        section
                        for planted_doc in row.owned.documents
                        if planted_doc.entity.id == brief.target.document_id
                        for section in planted_doc.entity.sections
                        if section.id == brief.id
                    ]
                    if len(sections) != 1:
                        raise ResumeRefused(f"{version}: the sealed spec holds no {brief.id}")
                    prose[brief.id] = sections[0].text
    return prose


__all__ = ["Assembler", "ResumeRefused", "resume_world"]
