"""The sealed worlds loaded as the evaluator loads them, live: the join proven on real bytes and
the sealed keys reproduced by today's rules.

The unit suite loads a throwaway world generated by today's code, so it cannot show the one
thing this does: that the rules as they are now still conclude what a world sealed earlier
holds. The golden world was sealed at generator version 14 and the evaluator derives every
verdict outside the probe set, and every expectation under an outage, with today's rules;
loading it runs world assembly's whole-world verification over its thirty keys, under both
views on every day of each stable interval, and refuses the world on any difference. A
failure here is a finding to rule before anything is graded, never something to patch
around.

Declared before the run, for every completed world the fixed inventory names: it loads;
it holds thirty scenarios; the version id the loader records for each of the three files
is the one the world's manifest recorded when the file was sealed; and the oracle, asked
under the normal condition, returns an answer for every scenario, which it does only when
that answer is the sealed key. A world sealed only as far as its truth pair has no scenario
specs to join and is not loaded here.

The inventory and the profile are E-003's (``test_sealed_bytes_round_trip``): the private
JSON in the stream through ``LEAVE_IMPACT_SEALED_INVENTORY``, the administrative profile,
the one identity that reads both buckets. The evaluator's own role cannot read the scenario
specs yet (a platform ticket, owed before the evaluation workflow's first dispatch), which
is why this runs from the workstation. Nothing is listed or written. A refusal prints the
scenarios and counts it concerns and the kinds of conclusion that differ, never a key's
content.
"""

from __future__ import annotations

import os
from collections import Counter
from typing import TYPE_CHECKING

import boto3
import pytest

from leaveimpact.adapters.manifest import ManifestStage, decode_manifest
from leaveimpact.adapters.object_store.s3 import S3ObjectReader, s3_client
from leaveimpact.core.facts import RunCondition
from leaveimpact.evaluator.oracle import Answerable, oracle_for
from leaveimpact.evaluator.sealed_world import KeysNotReproduced, load_sealed_world
from leaveimpact.world.plan import GOLDEN_SET_ROWS
from tests.live.test_sealed_bytes_round_trip import (
    INVENTORY_VARIABLE,
    SealedWorldCase,
    fetch,
    load_inventory,
)

if TYPE_CHECKING:
    from mypy_boto3_s3 import S3Client

pytestmark = pytest.mark.live

# What a whole-world finding can be about, beside a candidate's verdict: named so a failure
# says which kind of conclusion differs without naming a candidate or an artifact.
_KINDS = frozenset(
    {
        "outcome",
        "grounding",
        "impacts",
        "expected_conflicts",
        "expected_unknowns",
        "required_sources",
    }
)


def _worlds() -> list[SealedWorldCase]:
    path = os.environ.get(INVENTORY_VARIABLE)
    if path is None:
        return []
    with open(path, encoding="utf-8") as handle:
        return list(load_inventory(handle.read()).worlds)


@pytest.fixture(scope="module")
def s3() -> S3Client:
    if boto3.Session().get_credentials() is None:  # pyright: ignore[reportUnknownMemberType]
        pytest.skip("no AWS credentials in this process; run under the administrative profile")
    return s3_client(os.environ.get("AWS_REGION", "eu-central-1"))


@pytest.mark.parametrize("case", _worlds(), ids=lambda case: case.version[:8])
def test_a_completed_world_loads_and_todays_rules_reproduce_its_keys(
    s3: S3Client, case: SealedWorldCase
) -> None:
    truth = S3ObjectReader(s3, case.truth_bucket)
    world = S3ObjectReader(s3, case.world_bucket)
    try:
        loaded = load_sealed_world(case.version, truth, world)
    except KeysNotReproduced as refused:
        kinds = Counter(
            (finding.view, finding.subject if finding.subject in _KINDS else "a verdict")
            for finding in refused.findings
        )
        differing = ", ".join(
            f"{count} x {kind} ({view} view)" for (view, kind), count in sorted(kinds.items())
        )
        pytest.fail(f"{refused}; differing: {differing}")
    assert len(loaded.scenarios) == GOLDEN_SET_ROWS
    manifest = decode_manifest(fetch(s3, case.manifest), stage=ManifestStage.PROJECTED)
    for source in (loaded.world_spec, loaded.scenario_specs, loaded.truth_manifest):
        assert manifest.object_versions.get(source.key) == source.version_id, (
            f"{source.key}: the loader read version {source.version_id}, the manifest records "
            f"{manifest.object_versions.get(source.key)}"
        )
    normal = RunCondition.all_reachable()
    for scenario in loaded.scenarios:
        # ``oracle_for`` raises when its normal-condition answer is not the sealed key.
        assert isinstance(oracle_for(loaded, scenario, normal), Answerable), scenario.spec.id
