"""The domain, pure: what the real system believes, with no knowledge that a benchmark exists.

Holds the types every other package speaks (employee, team, work item, calendar event,
document, leave, and their ids), the predicate registry with each predicate's value
spec, the claim vocabulary with its per-type grading keys, ``RunContext`` and world
time, the fact base a run sees through a ``FactView`` under a ``RunCondition``, and
the deterministic rules — closed-world evaluation per declared evidence domain, the
system-of-record authority table that resolves conflicting observations, viability of
a person for a need, constraint checks. The investigator's deterministic core and the
evaluator call the same rule functions from here, which makes that sharing visible
instead of duplicated (the answer-key contract in DESIGN says why sharing rules is
safe and sharing code between generator and evaluator is not). Vendor-neutral ports
that both the generator and the investigator consume sit here too; an abstraction
that describes how one vendor works stays inside that vendor's adapter.

Boundary: never imports ``world`` — the production investigator depends on the domain
without depending on the benchmark that grades it; performs no I/O; reads no clock —
world time arrives in ``RunContext``, and the wall clock is read only at a composition
root. Populated step by step through the world milestone; the layout is the decision.

Callers import the public names from the package (``from leaveimpact.core import
Employee``); the module split is a navigation aid, not part of the contract.
"""

from leaveimpact.core import (
    authority,
    checks,
    claims,
    claims_json,
    closure,
    entities,
    enums,
    facts,
    ids,
    jsonshape,
    plans,
    predicates,
    refs,
    values,
    values_json,
    viability,
    worldtime,
)
from leaveimpact.core.authority import ConflictFinding, Resolution, conflicts_in, resolve
from leaveimpact.core.checks import (
    ABOUT_THE_ARTIFACT,
    ABOUT_THE_CANDIDATE,
    chain_problems,
    completeness_problems,
)
from leaveimpact.core.claims import (
    ARTIFACT_KINDS,
    AssessmentKey,
    AssessmentReason,
    AuthorityRule,
    CandidateAssessment,
    Claim,
    ClaimType,
    ConflictKey,
    Constraint,
    ConstraintKey,
    CoverageAction,
    CoverageActionKind,
    GradingKey,
    Impact,
    ImpactKey,
    ImpactSubtype,
    SourceConflict,
    Unknown,
    UnknownKey,
    UnknownReason,
    Verdict,
    require_well_formed,
    structural_problems,
)
from leaveimpact.core.claims_json import decode_claim, decode_claims, encode_claim, encode_claims
from leaveimpact.core.closure import (
    Closure,
    DerivedUnknownReason,
    KnownFalse,
    KnownTrue,
    Unresolved,
    any_true,
    establish,
    establish_any,
)
from leaveimpact.core.entities import (
    CalendarEvent,
    Comment,
    Component,
    Document,
    DocumentSection,
    Employee,
    Leave,
    Team,
    WorkItem,
)
from leaveimpact.core.enums import (
    DocumentKind,
    EmploymentType,
    EntityKind,
    Grade,
    LeaveKind,
    LeaveStatus,
    Source,
    WorkItemStatus,
)
from leaveimpact.core.facts import Fact, FactBase, FactKey, FactView, Gap, RunCondition
from leaveimpact.core.ids import (
    ClaimId,
    ClauseId,
    CommentId,
    ComponentId,
    DocumentId,
    EmployeeId,
    EventId,
    LeaveId,
    ScenarioId,
    SkillId,
    TeamId,
    WorkItemId,
    WorldVersion,
)
from leaveimpact.core.plans import (
    Violation,
    ViolationKind,
    expected_action,
    plan_violations,
    required_count,
)
from leaveimpact.core.predicates import REGISTRY, Predicate, PredicateName, predicate
from leaveimpact.core.refs import (
    PREFIX_BY_KIND,
    TARGET_KINDS_BY_SOURCE,
    EntityRef,
    EvidenceRef,
    clause_ref,
    comment_ref,
    component_ref,
    document_ref,
    employee_ref,
    event_ref,
    leave_ref,
    require_id,
    team_ref,
    work_item_ref,
)
from leaveimpact.core.values import (
    DATE_SPAN_VALUE,
    DATE_VALUE,
    INSTANT_SPAN_VALUE,
    REQUIREMENT_VALUE,
    SKILL_VALUE,
    TEXT_VALUE,
    Criterion,
    EmploymentTypeCriterion,
    FactValue,
    Observation,
    Requirement,
    SkillCriterion,
    ValueKind,
    ValueSpec,
    entity_value,
    enum_value,
)
from leaveimpact.core.values_json import decode_value, encode_value
from leaveimpact.core.viability import (
    Assessment,
    Need,
    ResolvedRequirement,
    applicable_requirements,
    assess,
    assess_impact,
    need_of,
)
from leaveimpact.core.worldtime import DateSpan, InstantSpan, RunContext, local_date

# The submodules are listed so the rendered reference keeps their docstrings — each
# carries the why of its part — beside the public names.
__all__ = [
    "authority",
    "checks",
    "claims",
    "claims_json",
    "closure",
    "entities",
    "enums",
    "facts",
    "ids",
    "jsonshape",
    "plans",
    "predicates",
    "refs",
    "values",
    "values_json",
    "viability",
    "worldtime",
    "ABOUT_THE_ARTIFACT",
    "ABOUT_THE_CANDIDATE",
    "ARTIFACT_KINDS",
    "DATE_SPAN_VALUE",
    "DATE_VALUE",
    "INSTANT_SPAN_VALUE",
    "PREFIX_BY_KIND",
    "REGISTRY",
    "REQUIREMENT_VALUE",
    "SKILL_VALUE",
    "TARGET_KINDS_BY_SOURCE",
    "TEXT_VALUE",
    "Assessment",
    "AssessmentKey",
    "AssessmentReason",
    "AuthorityRule",
    "CalendarEvent",
    "CandidateAssessment",
    "Claim",
    "ClaimId",
    "ClaimType",
    "ClauseId",
    "Closure",
    "Comment",
    "CommentId",
    "Component",
    "ComponentId",
    "ConflictFinding",
    "ConflictKey",
    "Constraint",
    "ConstraintKey",
    "CoverageAction",
    "CoverageActionKind",
    "Criterion",
    "DateSpan",
    "DerivedUnknownReason",
    "Document",
    "DocumentId",
    "DocumentKind",
    "DocumentSection",
    "Employee",
    "EmployeeId",
    "EmploymentType",
    "EmploymentTypeCriterion",
    "EntityKind",
    "EntityRef",
    "EventId",
    "EvidenceRef",
    "Fact",
    "FactBase",
    "FactKey",
    "FactValue",
    "FactView",
    "Gap",
    "Grade",
    "GradingKey",
    "Impact",
    "ImpactKey",
    "ImpactSubtype",
    "InstantSpan",
    "KnownFalse",
    "KnownTrue",
    "Leave",
    "LeaveId",
    "LeaveKind",
    "LeaveStatus",
    "Need",
    "Observation",
    "Predicate",
    "PredicateName",
    "Requirement",
    "ResolvedRequirement",
    "Resolution",
    "RunCondition",
    "RunContext",
    "ScenarioId",
    "SkillCriterion",
    "SkillId",
    "Source",
    "SourceConflict",
    "Team",
    "TeamId",
    "Unknown",
    "UnknownKey",
    "UnknownReason",
    "Unresolved",
    "ValueKind",
    "ValueSpec",
    "Verdict",
    "Violation",
    "ViolationKind",
    "WorkItem",
    "WorkItemId",
    "WorkItemStatus",
    "WorldVersion",
    "any_true",
    "applicable_requirements",
    "assess",
    "assess_impact",
    "chain_problems",
    "clause_ref",
    "comment_ref",
    "completeness_problems",
    "component_ref",
    "conflicts_in",
    "decode_claim",
    "decode_claims",
    "decode_value",
    "document_ref",
    "employee_ref",
    "encode_claim",
    "encode_claims",
    "encode_value",
    "entity_value",
    "enum_value",
    "establish",
    "establish_any",
    "event_ref",
    "expected_action",
    "leave_ref",
    "local_date",
    "need_of",
    "plan_violations",
    "predicate",
    "require_id",
    "require_well_formed",
    "required_count",
    "resolve",
    "structural_problems",
    "team_ref",
    "work_item_ref",
]
